const host = "https://chineseserver-4jwzf0ue.b4a.run/";
export const register = `${host}auth/register`;
export const login = `${host}auth/login`;
export const content = `${host}content`;
export const likeURL = `${host}content/like`;
export const createURL = `${host}content/create`;
export const getPost = `${host}content/fetch`;
export const getReplies = `${host}content/replies`
export const likeCmntURL = `${host}content/likecmnt`;
export const addCmnt = `${host}content/comment`;